#!/usr/bin/env php
<?php

/**
 * This file is part of Mactronique EDF TeleReleve package.
 *
 * @author Jean-Baptiste Nahan <jbnahan@gmail.com>
 * @copyright 2016 - Jean-Baptiste Nahan
 * @license MIT
 */

require __DIR__.'/vendor/autoload.php';

use Mactronique\TeleReleve\TeleReleveApplication;

$application = new TeleReleveApplication();
$application->run();